In [87]:
import requests
from bs4 import BeautifulSoup
from pandas import pivot_table

def movie_crawling(start_page=1, last_page=10):
    
    
    df = pd.DataFrame(columns=['movie','name'])

    
    for i in range(start_page, last_page+1):
        response = requests.get("https://movie.naver.com/movie/point/af/list.nhn?&page={}".format(i))
        dom = BeautifulSoup(response.content, "html.parser")
        datas = dom.select("#old_content  .list_netizen  tbody tr")
        for data in datas:
            point = data.select_one(".point").text
            title = data.select_one(".title .movie").text
            user = data.select_one(".num .author").text
            df = df.append({'movie': title, 'name':user,'point':point}, ignore_index=True)


        
        

    return df
# naver(1, 100)
# naver_df = naver()
# naver_df.tail()

import time
%time
frames = []
for page in range(10):
    frames.append(movie_crawling(page*100 + 1, (page+1)*100))
    
result_df = pd.concat(frames)

In [135]:
df = pd.read_csv('movie_crawling.csv')
df.tail()

      Unnamed: 0              movie      name  point
9995        9995  주먹왕 랄프 2: 인터넷 속으로  blin****     10
9996        9996             내안의 그놈  kjj_****     10
9997        9997             내안의 그놈  wjse****     10
9998        9998             구스 베이비  mihy****     10
9999        9999                언더독  rrup****     10

In [136]:
data_df = pivot_table(df, values='point', index='name', columns='movie', aggfunc=np.sum, fill_value=0)
data_df.tail()

movie,...ing,12 라운드,12 몽키즈,127 시간,13 구역,13층,1987,"1991, 봄",2012,2025 지구전쟁: 얼리전스 오브 파워,...,황해,회사원,회초리,후세: 말하지 못한 내 사랑,후크,휘트니,휴게소,흥부: 글로 세상을 바꾼 자,히든 페이스,히든 피겨스
name,,,,,,,,,,,,,,,,,,,,,
zzun****,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzz3****,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzz5****,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzzx****,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzzz****,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [137]:
data_df.index = data_df.index.astype(str).str[:-4]
data_df.tail()

movie,...ing,12 라운드,12 몽키즈,127 시간,13 구역,13층,1987,"1991, 봄",2012,2025 지구전쟁: 얼리전스 오브 파워,...,황해,회사원,회초리,후세: 말하지 못한 내 사랑,후크,휘트니,휴게소,흥부: 글로 세상을 바꾼 자,히든 페이스,히든 피겨스
name,,,,,,,,,,,,,,,,,,,,,
zzun,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzz3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzz5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzzx,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
zzzz,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [141]:
len(data_df)

7044

In [138]:
from similarity import similarity

In [139]:
movie_recommend = similarity(data_df, 'zzzz', 3)

In [140]:
movie_recommend.recommend()

KeyboardInterrupt:

In [102]:
# parser.py
import requests
from bs4 import BeautifulSoup as bs
import time

from multiprocessing import Pool # Pool import하기


def get_links(): # 블로그의 게시글 링크들을 가져옵니다.
    req = requests.get('https://beomi.github.io/beomi.github.io_old/')
    html = req.text
    soup = bs(html, 'html.parser')
    my_titles = soup.select(
        'h3 > a'
        )
    data = []

    for title in my_titles:
        data.append(title.get('href'))
    return data

# print(get_links())

def get_content(link):
    abs_link = 'https://beomi.github.io'+link
    req = requests.get(abs_link)
    html = req.text
    soup = bs(html, 'html.parser')
    # 가져온 데이터로 뭔가 할 수 있겠죠?
    # 하지만 일단 여기서는 시간만 확인해봅시다.
    print(soup.select('h1')[0].text) # 첫 h1 태그를 봅시다.
    
# get_content(get_links()[0])
# get_content(get_links()[1])

# for i in range(10):
#     get_content(get_links()[i])
ls = []

if __name__=='__main__':
#     start_time = time.time()
    pool = Pool(processes=4) # 4개의 프로세스를 사용합니다.

    pool.map(get_content, get_links()) # get_contetn 함수를 넣어줍시다.
#     print("--- %s seconds ---" % (time.time() - start_time))

print(ls)

Celery로 TelegramBot 알림 보내기
나만의 웹 크롤러 만들기(2): Login with Session
Django에 Social Login 붙이기: Django세팅부터 Facebook/Google 개발 설정까지
나만의 웹 크롤러 만들기(4): Django로 크롤링한 데이터 저장하기
나만의 웹 크롤러 만들기 with Requests/BeautifulSoup
Virtualenv/VirtualenvWrapper OS별 설치&이용법
Django에 Custom인증 붙이기
[DjangoTDDStudy] #02: UnitTest 이용해 기능 테스트 하기
나만의 웹 크롤러 만들기(3): Selenium으로 무적 크롤러 만들기
[DjangoTDDStudy] #00: 스터디를 시작하며
[React Native 번역]#01: 시작하기
[DjangoTDDStudy] #01: 개발환경 세팅하기(Selenium / ChromeDriver)
CKEditor의 라이센스와 오픈소스 라이센스
Chrome Native Adblockr 대체하기
ReactNative The Basis 번역을 끝냈습니다.
Fabric Put 커맨드가 No Such File Exception을 반환할 때 해결법
[번역] 장고(Django)와 함께하는 Celery 첫걸음
CustoMac 설치 분투기
Ubuntu14.04에서 Python3기반 virtualenvwrapper 설치
Fabric for Python3 (Fabric3)
맥에서 윈도RDP로 접속시 한영전환하기.
Windows에서 pip로 mysqlclient 설치 실패시(python3.4/3.5)
mac OS X에서 pip virtualenvwrapper 설치 시 uninstalling six 에서 Exception 발생 시
pip로 mysqlclient설치 중 mac os x에서 egg_info / OSError 발생시 대처방법
Ubuntu14.04에 OhMyZsh 설치
Ubuntu14.04에서 pip로 mysqlclient 설치 실패시
[]

Process ForkPoolWorker-24:
Process ForkPoolWorker-21:
Process ForkPoolWorker-23:
Process ForkPoolWorker-22:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 352, in get
    res = self._reader.recv_bytes()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
KeyboardInterrupt
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt